version: '3'

services:
  web:
    image: carldu/online-tool
    ports:
      - '80:80'
    container_name: 'web'
  db:
    image: carldu/online-tool-db
    ports:
      - '5433:5432'
    container_name: 'db'
    privileged: true
    environment:
      POSTGRES_PASSWORD: '123123'
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - /home/server/pg_data:/var/lib/postgresql/data'
  postgrest:
    image: postgrest/postgrest
    container_name: 'api'
    ports:
      - '3000:3000'
    links:
      - db:db
    depends_on:
      - db
    environment:
      PGRST_DB_URI: 'postgres://online_tool_user:123123@db:5432/online_tool'
      PGRST_DB_SCHEMA: 'public'
      PGRST_DB_ANON_ROLE: 'online_tool_user'
  swagger:
    image: swaggerapi/swagger-ui
    container_name: 'swagger'
    ports:
      - '8080:8080'
    environment:
      API_URL: http://localhost:3000/
